# Remove `_example` from filename if you want to use the FTP

# Switch FTP Server Information goes here
ftp_server="10.0.0.143" # The switch's IP goes here
ftp_port=5000 # The port number for your switch's FTP server (ftp-sys-light default is 5000)
ftp_username="" # FTP username (Leave empty for Anonymous)
ftp_password="" # FTP password (Leave empty for Anonymous)
ftp_path_upload="/ultimate/mods/Add Songs" # Where to upload the files onto the server

# Optional
# ftp_autoconnect="True" #  Whether to autoconnect or not. Set to True or False
# ftp_clean_dir="True" # Whether to clean the directory on the server (WARNING: THIS WILL REMOVE EVERYTHING IN THE SPECIFIED PATH UPLOAD)
# ftp_clean_dir_no_prompt="True" # Whether or not you want to get a prompt confirming to clean the directory